# Dockerfile
FROM oracleinanutshell/oracle-xe-11g

MAINTAINER Javier Etchepare <gerardo.etchepare@gmail.com>

ADD init.sql /docker-entrypoint-initdb.d/
ADD script.sh /docker-entrypoint-initdb.d/

# Volumes     
VOLUME ["/docker-entrypoint-initdb.d"]
